### ISSUE TITLE
Differences from esformatter-asi

### ISSUE THREAD

**Issue by nhooyr** [nilsboy/es-strip-semicolons#1]
Did you have any problems with https://github.com/nathanboktae/esformatter-asi that led to you creating this?

**Comment by nilsboy** [comment]
It's been a while when I started this - I tried lots of different formatters that didn't work for me. I'm not sure I tried your suggestion.
These days I'm mostly using eslint with --fix.

**Comment by nhooyr** [comment]
Does it strips all unnecessary semicolons?

**Comment by nilsboy** [comment]
It should - but I gonna deprecate it.
Please use eslint --fix with the "semi" rule and option "never".

**Comment by nhooyr** [comment]
I was asking about `eslint --fix`, not this program. Glad to know it does, thanks!
